### ISSUE TITLE
`main` in package.json points to nonexistent file

### ISSUE THREAD

**Issue by merkys** [inventaire/wikidata-lang#1]
`main` in package.json points to nonexistent file:
https://github.com/inventaire/wikidata-lang/blob/82e8450d699a1e58276e93fd4b2c0a084376ef73/package.json#L5

It seems that at some point files from `indexes/` were moved to the base directory, and this action was undone later. I think `main` now should be updated.

**Comment by maxlath** [comment]
Indeed! (I didn't notice as I now tend to [directly import the desired mapping](https://github.com/inventaire/inventaire/search?q=wikidata-lang&type=code)). That should have been fixed by aedcc16, published in `v4.1.1`

**Comment by merkys** [comment]
Thanks!
