### ISSUE TITLE
Tests fail due to module reorganization

### ISSUE THREAD

**Issue by merkys** [inventaire/wikidata-lang#2]
Mocha tests fail due to imports not adapted to module reorganization:
https://github.com/inventaire/wikidata-lang/blob/2044b1ca5300e802766edbf9d6867f05db6ee9bf/test/indexes.js#L3-L4

`by_wd_id.js` now resides in `indexes/`, and `by_code` seems to be gone (renamed to `indexes/by_any_code.js` maybe?)

**Comment by maxlath** [comment]
fixed in f141336 and published in `v4.1.2`

**Comment by merkys** [comment]
Thanks for the fix!
